[package]
name = "lab2-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
num-bigint = "0.4"
quadratic = "0.3.1"
rand = "0.8"
